[default]

[default.default_budget_reader]
# Configurações gerais do sistema
SOURCE_FILE_COLUMN_NAME = "SOURCE_FILE"
SHEET_NAME_COLUMN_NAME = "SHEET_NAME"

[default.default_budget_reader.default_sheet]
# Configurações da aba padrão a ser lida
name = ""  # Nome da aba padrão (deixe vazio para todas as abas)
sheet_candidates = ["LPU", "01"]  # Candidatos a nomes de abas
pattern_default = "default01"

[default.default_budget_reader.expected_columns.default01]
# Colunas esperadas para o padrao "default01"
columns = [
    "ID",  # Identificador unico do item
    "DESCRICAO",  # Nome do item
    "UN.",  # Unidade de medida
    "UNITARIO",  # Preco unitario
    "COMENTARIO",  # Comentarios adicionais
    "QUANTIDADE",  # Quantidade do item
    "TOTAL"  # Valor total do item
]

[default.default_budget_reader.expected_columns.default02]
# Colunas esperadas para o padrao "default02"
columns = [
    "ITEM",  # ID da categoria
    "DESCRICAO",  # Nome do item
    "UN",  # Unidade de medida
    "QUANT",  # Quantidade do item
    "PRECO UNITARIO",  # Preco unitario
    "",  # Coluna vazia
    "PRECO TOTAL"  # Valor total do item
]

[default.default_budget_reader.expected_columns.default03]
# Colunas esperadas para o padrao "default03"
columns = [
    "ITEM",  # ID da categoria
    "DESCRICAO",  # Nome do item
    "UN",  # Unidade de medida
    "QUANT",  # Quantidade do item
    "PRECO UNITARIO",  # Preco unitario
    "PARCIAL",  # Preco parcial
    "TOTAL"  # Valor total do item
]

[default.default_budget_reader.alternative_columns.default01]
# Colunas alternativas minimas para o padrao "default01"
columns = [
    "ID",  # Identificador unico do item
    "DESCRICAO",  # Nome do item
    "UNITARIO",  # Preco unitario
    "QUANTIDADE"  # Quantidade do item
]

[default.default_budget_reader.alternative_columns.default02]
# Colunas alternativas minimas para o padrao "default02"
columns = [
    "DESCRICAO",  # Nome do item
    "QUANT",  # Quantidade do item
    "P.U."  # Preco unitario
]

[default.default_budget_reader.alternative_columns.default03]
# Colunas alternativas minimas para o padrao "default03"
columns = [
    "ITEM",  # Identificador unico do item
    "DESCRICAO",  # Nome do item
    "QUANT",  # Quantidade do item
    "PRECO UNITARIO"  # Preco unitario
]

[default.default_budget_reader.default01.result]
# Rename de colunas para o padrao "default01"
dict_rename = {"ID" = "ID", "DESCRICAO" = "NOME", "UN." = "UNIDADE", "UNITARIO" = "PRECO PAGO", "COMENTARIO" = "COMENTARIO", "QUANTIDADE" = "QUANTIDADE", "TOTAL" = "VALOR TOTAL"}

[default.default_budget_reader.default02.result]
# Rename de colunas para o padrao "default02"
dict_rename = {"ITEM" = "ID", "DESCRICAO" = "NOME", "UN" = "UNIDADE", "QUANT" = "QUANTIDADE", "PRECO UNITARIO" = "PRECO PAGO", "" = "", "PRECO TOTAL" = "VALOR TOTAL"}

[default.default_budget_reader.default03.result]
# Rename de colunas para o padrao "default03"
dict_rename = {"ITEM" = "ID", "DESCRICAO" = "NOME", "UN" = "UNIDADE", "QUANT" = "QUANTIDADE", "PRECO UNITARIO" = "PRECO PAGO", "PARCIAL" = "PRECO PARCIAL", "PRECO TOTAL" = "VALOR TOTAL"}

[default.default_budget_reader.result]
# Colunas esperadas no final do processo
list_result_columns = ["ID", "NOME", "UNIDADE", "PRECO PAGO", "COMENTÁRIO", "QUANTIDADE", "VALOR TOTAL", "SOURCE_FILE", "SHEET_NAME"]
file_name_output = "01_BASE_RESULTADO_ORCAMENTOS_CONCATENADOS.xlsx" # Nome do arquivo de saída final
name_sheet_output_tables = "Tables"  # Nome da aba do arquivo de saída final (Tabelas de orçamento)
name_sheet_output_metadata = "Metadata"  # Nome da aba de metadados do arquivo de saída final (Metadados de orçamento)

[default.default_budget_reader.filtros]
# Filtros aplicados no pós-processamento
dict_filtros = {"QUANTIDADE" = "greater_than:0"}

[default.default_budget_reader.dir_outputs]
# Diretório de saída padrão
path = "data/outputs"  # Caminho para salvar os arquivos de saída